version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # These volumes are for persistent data. They are NOT in the /app directory.
      - chroma_data:/persistent_data/chroma_db
      - pdf_data:/persistent_data/data
      # This volume is for live code reloading during development.
      - ./backend:/app
    env_file:
      - .env
    restart: unless-stopped
    environment:
      # Pass the persistent paths to the Python application
      - CHROMA_DB_PATH=/persistent_data/chroma_db
      - PDF_DATA_PATH=/persistent_data/data

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  chroma_data:
  pdf_data: